/*****************************************************************************
 Sphinx C-- library (C) 2000.
 FILE:        GRAPHICS.H
 DESCRIPTION: Definitions for Graphics Package.

 LAST MODIFIED:
 ----------------------------------------------------------------------------

To do create:
 arc
 bar
 bar3d
 circle
 cleardevice
 clearviewport
 closegraph
 detectgraph
 drawpoly
 ellipse
 fillellipse
 fillpoly
 floodfill
 getarccoords
 getaspectratio
 getbkcolor
 getcolor
 detdefaultpalette
 getdrivername
 getfillpattern
 getfillsettings
 getgraphmode
 getimage
 getlinesettings
 getmaxcolor
 getmaxmode
 getmaxx
 getmaxy
 getmodename
 getmoderange
 getpallete
 getpalletesize
 getpixel
 gettextsettings
 getviewsettings
 getx
 gety
 graphdefaults
 grapherrormsg
 _graphfreemem
 _graphgetmem
 graphresult
 imagesize
 initgraph
 installuserdriver
 installuserfont
 line
 linerel
 lineto
 moverel
 moveto
 outtext
 outtextxy
 pieslice
 putimage
 putpixel
 rectangle
 registerbgidriver
 registerbgifont
 restorecrtmode
 sector
 setactivepage
 setallpalette
 setaspectratio
 setbkcolor
 setcolor
 setfillpattern
 setfillstyle
 setgraphbufsize
 setgraphmode
 setlinestyle
 setpalette
 setrgbpalette
 settextjustify
 settextstyle
 setusercharsize
 setviewport
 setvisualpage
 setwritemode
 textheight
 textwidth

*****************************************************************************/
